### ISSUE TITLE
I can't send any email after upgrade to Laravel 9

### ISSUE THREAD

**Issue by chimilevschi** [egulias/EmailValidator#315]
After upgrading to Laravel 9, I can not send any email (registration email, forgot password or any other email).

Fatal Error: Symfony\Component\ErrorHandler\Error\FatalError: Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::isValid(string $email, Egulias\EmailValidator\EmailLexer $emailLexer): bool must be compatible with Egulias\EmailValidator\Validation\EmailValidation::isValid($email, Egulias\EmailValidator\EmailLexer $emailLexer) in file /home/clevada/clevada/vendor/egulias/email-validator/src/Validation/MessageIDValidation.php on line 23

Any help, please?

**Comment by chimilevschi** [comment]
I fixed this.
I remove vendor folder and update composer. 
Now it works fine.

**Comment by Salah-1** [comment]
I have the same error and removing vendor folder + composer update doesn't solve it. What else can be done ?
